### ISSUE TITLE
*GUIButton not defined?

### ISSUE THREAD

**Issue by jose-vm** [MCMrARM/UILib#2]
I was implementing UILib in my addon, and this message appeared while building it with AIDE.

**Comment by ghost** [comment]
Just write into code: 
include "elements/GUIButton.cpp"

**Comment by ghost** [comment]
@NeoKat You should not use this library. There is a better way to do what this library do and this library is outdated.

**Comment by ghost** [comment]
@InusualZ What way?

**Comment by MCMrARM** [comment]
Headers. Not public yet. It'll be soon though.
